sudo: false
language: ruby
rvm:
- 2.3.3
before_install: gem install bundler -v 1.13.6
notifications:
  slack:
    secure: K+I4otkeX0yMPQing/KbcB5A/FKWo4aNFeRl7PuQ9hB1K7f2rRr0s2uvkfFsXYYFJrxWNhNnPoiiJNAmOBzmFljcIAGm5k5qPfmjFeVTFsv1lEZjfAa2UbCKgCGi79P48BvZ4zXO1I/uZsNUBkVPAfxZSq+aG3tudPXmXOEeTjMMNE6czYr49qrLsQPh7ezx2431Zm+qMqzSoqW7aOzZjgZvuc8IllrrBWO2cstD/8LkLrYVrY+MJbxM8kT6ZXbCXDisu/jSN/ChIVCFfEmYjavdkCrIyMN3gqFzwBnjFtco9YlPRqyA4DOWFzXmIzOSh77rEskF+noaPS2dUMt6g/32GQbwRR+x/YvJkqizyOwLky2H7aVw2pCgZnIGIshXxZPIUwxriML/O0MpkKRDnFcc8kzeL1IOqQauxRxq9woSZ68pFyVP4dc5JT1cuMGJK0/vWCUKnPSyV9wjUNJQXHV907Fxh+aW398JpPUEeAsjMO8erwWd0w8q4qYDEamoc7+pjz+HEJJjlVYseDR3CN3bpR3vcizpIPHTUlTTRMNY+KTbPRMam+9ZLJzv+SFVZ58hjJQK8aIW0tc51bhP2cuzNfmX2YcYEJ6DQvCWdnj7V6gKOHCB/BebfIUmdvRGyew2mrZSUfXPTAAlnwiRhf5IDzIulR0GusgQiqa5tmU=
