sudo: false
env:
  global:
    - secure: lSqmXKeSjlvn9vtmPhEFZCHdeVjyD0toqByvIJVH8/M7KZP9EBkG6p0l/QsGQM+Tid7EjLeDrKkZE7LytvhyS9/0lESpXl20RtQWqOhd+03qdTKRO5SgL6BwonV7dv3VfGUpkwuCOUSJpOPN/xHu1QidyHZuQ0GpKP4gIZkNIten1Rm5hxJ1MxHzg7pu6F6XkyHeamOcoUeqE1eDRRz/g0+Vc7EzG+jAzd3gNu3fHW9LZ8qHh0f7M86U/nuIbQmldvhwbXK3HZk4DLbBg7nVj74yhskNXAWI61dirzHRJkETxaH8ZK04jkQj5yNdD5K+mprh3hj0gSVn2cWqljd8bWe7uutQ7yeye9c3wza0gj5qVekZwLemwFvlIL0JicPE9fjhmOfliYIA/y6ruvTL+JIxCToNDiLlB0XY4KVl1c+mOmSopmdUrx22OA4n15pdOnXMNs7VPTuKu1JgvZlWY2Pkh3QIT5+5iTqgkt0b0OjX0lHnUZZW26v8Rt4eeAyObGsbtxEWUt2tLvV7szVJw8KY6kYCb8dDvgedV3xrzHMkoh3O+UcZj42UnKXOLDL8kJO0RS1j5AbpURFnTlcqtAKppkMigboCJtWh/KJNajWvBeBs2PKZmE7L7PZVLU0Igw03zLi+LpP0FXN2SFqcecO09Ozl7OcjWH1QTZmCjig=
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: K+I4otkeX0yMPQing/KbcB5A/FKWo4aNFeRl7PuQ9hB1K7f2rRr0s2uvkfFsXYYFJrxWNhNnPoiiJNAmOBzmFljcIAGm5k5qPfmjFeVTFsv1lEZjfAa2UbCKgCGi79P48BvZ4zXO1I/uZsNUBkVPAfxZSq+aG3tudPXmXOEeTjMMNE6czYr49qrLsQPh7ezx2431Zm+qMqzSoqW7aOzZjgZvuc8IllrrBWO2cstD/8LkLrYVrY+MJbxM8kT6ZXbCXDisu/jSN/ChIVCFfEmYjavdkCrIyMN3gqFzwBnjFtco9YlPRqyA4DOWFzXmIzOSh77rEskF+noaPS2dUMt6g/32GQbwRR+x/YvJkqizyOwLky2H7aVw2pCgZnIGIshXxZPIUwxriML/O0MpkKRDnFcc8kzeL1IOqQauxRxq9woSZ68pFyVP4dc5JT1cuMGJK0/vWCUKnPSyV9wjUNJQXHV907Fxh+aW398JpPUEeAsjMO8erwWd0w8q4qYDEamoc7+pjz+HEJJjlVYseDR3CN3bpR3vcizpIPHTUlTTRMNY+KTbPRMam+9ZLJzv+SFVZ58hjJQK8aIW0tc51bhP2cuzNfmX2YcYEJ6DQvCWdnj7V6gKOHCB/BebfIUmdvRGyew2mrZSUfXPTAAlnwiRhf5IDzIulR0GusgQiqa5tmU=
